import type { Theme } from './types';

// FIX: Define base themes in a separate object to avoid self-reference during initialization.
const baseThemes: Record<string, Theme> = {
  indigo: {
    name: "Indigo",
    colors: {
      mainBg: "bg-slate-50",
      mainText: "text-slate-800",
      cardBg: "bg-white",
      cardHeader: "text-slate-900",
      secondaryText: "text-slate-600",
      mutedText: "text-slate-500",
      primary: "bg-indigo-600",
      primaryText: "text-white",
      primaryAccent: "bg-indigo-500",
      primaryAccentLight: "bg-indigo-400",
      primaryMuted: "text-indigo-700",
      primaryMutedBg: "bg-indigo-100",
      primaryBorder: "border-indigo-200",
      primaryLightestBg: "bg-indigo-50",
      ring: "focus:ring-indigo-500",
      button: {
        hoverBg: "hover:bg-slate-200",
        disabledBg: "bg-slate-300",
        disabledText: "text-slate-400",
      },
      classType: {
        lecture: "bg-blue-100 text-blue-800",
        seminar: "bg-green-100 text-green-800",
        lab: "bg-yellow-100 text-yellow-800",
      },
      divider: "border-slate-200",
    },
  },
  rose: {
    name: "Rose",
    colors: {
      mainBg: "bg-stone-50",
      mainText: "text-stone-800",
      cardBg: "bg-white",
      cardHeader: "text-stone-900",
      secondaryText: "text-stone-600",
      mutedText: "text-stone-500",
      primary: "bg-rose-600",
      primaryText: "text-white",
      primaryAccent: "bg-rose-500",
      primaryAccentLight: "bg-rose-400",
      primaryMuted: "text-rose-700",
      primaryMutedBg: "bg-rose-100",
      primaryBorder: "border-rose-200",
      primaryLightestBg: "bg-rose-50",
      ring: "focus:ring-rose-500",
      button: {
        hoverBg: "hover:bg-stone-200",
        disabledBg: "bg-stone-300",
        disabledText: "text-stone-400",
      },
      classType: {
        lecture: "bg-rose-100 text-rose-800",
        seminar: "bg-amber-100 text-amber-800",
        lab: "bg-fuchsia-100 text-fuchsia-800",
      },
      divider: "border-stone-200",
    },
  },
  teal: {
    name: "Teal",
    colors: {
      mainBg: "bg-slate-50",
      mainText: "text-slate-800",
      cardBg: "bg-white",
      cardHeader: "text-slate-900",
      secondaryText: "text-slate-600",
      mutedText: "text-slate-500",
      primary: "bg-teal-600",
      primaryText: "text-white",
      primaryAccent: "bg-teal-500",
      primaryAccentLight: "bg-teal-400",
      primaryMuted: "text-teal-700",
      primaryMutedBg: "bg-teal-100",
      primaryBorder: "border-teal-200",
      primaryLightestBg: "bg-teal-50",
      ring: "focus:ring-teal-500",
      button: {
        hoverBg: "hover:bg-slate-200",
        disabledBg: "bg-slate-300",
        disabledText: "text-slate-400",
      },
      classType: {
        lecture: "bg-cyan-100 text-cyan-800",
        seminar: "bg-emerald-100 text-emerald-800",
        lab: "bg-lime-100 text-lime-800",
      },
      divider: "border-slate-200",
    },
  },
  amber: {
    name: "Amber",
    colors: {
      mainBg: "bg-stone-100",
      mainText: "text-stone-800",
      cardBg: "bg-white",
      cardHeader: "text-stone-900",
      secondaryText: "text-stone-600",
      mutedText: "text-stone-500",
      primary: "bg-amber-500",
      primaryText: "text-stone-900",
      primaryAccent: "bg-amber-400",
      primaryAccentLight: "bg-amber-300",
      primaryMuted: "text-amber-700",
      primaryMutedBg: "bg-amber-100",
      primaryBorder: "border-amber-300",
      primaryLightestBg: "bg-amber-50",
      ring: "focus:ring-amber-500",
      button: {
        hoverBg: "hover:bg-stone-200",
        disabledBg: "bg-stone-300",
        disabledText: "text-stone-500",
      },
      classType: {
        lecture: "bg-orange-100 text-orange-800",
        seminar: "bg-lime-100 text-lime-800",
        lab: "bg-yellow-100 text-yellow-800",
      },
      divider: "border-stone-200",
    },
  },
  slate: {
    name: "Slate",
    colors: {
      mainBg: "bg-slate-900",
      mainText: "text-slate-300",
      cardBg: "bg-slate-800",
      cardHeader: "text-slate-100",
      secondaryText: "text-slate-400",
      mutedText: "text-slate-500",
      primary: "bg-slate-500",
      primaryText: "text-white",
      primaryAccent: "bg-slate-600",
      primaryAccentLight: "bg-slate-400",
      primaryMuted: "text-slate-400",
      primaryMutedBg: "bg-slate-700/50",
      primaryBorder: "border-slate-600",
      primaryLightestBg: "bg-slate-700/30",
      ring: "focus:ring-slate-500",
      button: {
        hoverBg: "hover:bg-slate-700",
        disabledBg: "bg-slate-600",
        disabledText: "text-slate-400",
      },
      classType: {
        lecture: "bg-indigo-900 text-indigo-300",
        seminar: "bg-emerald-900 text-emerald-300",
        lab: "bg-amber-900 text-amber-300",
      },
      divider: "border-slate-700",
    },
  },
  'dark-sky': {
    name: "Dark Sky",
    colors: {
      mainBg: "bg-slate-900",
      mainText: "text-slate-300",
      cardBg: "bg-slate-800",
      cardHeader: "text-slate-100",
      secondaryText: "text-slate-400",
      mutedText: "text-slate-500",
      primary: "bg-sky-500",
      primaryText: "text-white",
      primaryAccent: "bg-sky-600",
      primaryAccentLight: "bg-sky-400",
      primaryMuted: "text-sky-400",
      primaryMutedBg: "bg-sky-900/50",
      primaryBorder: "border-sky-700",
      primaryLightestBg: "bg-sky-900/30",
      ring: "focus:ring-sky-500",
      button: {
        hoverBg: "hover:bg-slate-700",
        disabledBg: "bg-slate-600",
        disabledText: "text-slate-400",
      },
      classType: {
        lecture: "bg-indigo-900 text-indigo-300",
        seminar: "bg-emerald-900 text-emerald-300",
        lab: "bg-amber-900 text-amber-300",
      },
      divider: "border-slate-700",
    },
  },
};

export const themes: Record<string, Theme> = {
  ...baseThemes,
  red: {
    name: "Red",
    colors: {
      // FIX: Reference `baseThemes` instead of `themes` to avoid using a variable during its declaration.
      ...baseThemes.indigo.colors,
      primary: "bg-red-600",
      primaryAccent: "bg-red-500",
      primaryAccentLight: "bg-red-400",
      primaryMuted: "text-red-700",
      primaryMutedBg: "bg-red-100",
      primaryBorder: "border-red-200",
      primaryLightestBg: "bg-red-50",
      ring: "focus:ring-red-500",
    },
  },
  green: {
    name: "Green",
    colors: {
      // FIX: Reference `baseThemes` instead of `themes` to avoid using a variable during its declaration.
      ...baseThemes.indigo.colors,
      primary: "bg-green-600",
      primaryAccent: "bg-green-500",
      primaryAccentLight: "bg-green-400",
      primaryMuted: "text-green-700",
      primaryMutedBg: "bg-green-100",
      primaryBorder: "border-green-200",
      primaryLightestBg: "bg-green-50",
      ring: "focus:ring-green-500",
    },
  },
  sky: {
    name: "Sky",
    colors: {
      // FIX: Reference `baseThemes` instead of `themes` to avoid using a variable during its declaration.
      ...baseThemes.indigo.colors,
      primary: "bg-sky-600",
      primaryAccent: "bg-sky-500",
      primaryAccentLight: "bg-sky-400",
      primaryMuted: "text-sky-700",
      primaryMutedBg: "bg-sky-100",
      primaryBorder: "border-sky-200",
      primaryLightestBg: "bg-sky-50",
      ring: "focus:ring-sky-500",
    },
  },
  violet: {
    name: "Violet",
    colors: {
      // FIX: Reference `baseThemes` instead of `themes` to avoid using a variable during its declaration.
      ...baseThemes.indigo.colors,
      primary: "bg-violet-600",
      primaryAccent: "bg-violet-500",
      primaryAccentLight: "bg-violet-400",
      primaryMuted: "text-violet-700",
      primaryMutedBg: "bg-violet-100",
      primaryBorder: "border-violet-200",
      primaryLightestBg: "bg-violet-50",
      ring: "focus:ring-violet-500",
    },
  },
  'dark-red': {
    name: "Dark Red",
    colors: {
      // FIX: Reference `baseThemes` instead of `themes` to avoid using a variable during its declaration.
      ...baseThemes['dark-sky'].colors,
      primary: "bg-red-500",
      primaryAccent: "bg-red-600",
      primaryAccentLight: "bg-red-400",
      primaryMuted: "text-red-400",
      primaryMutedBg: "bg-red-900/50",
      primaryBorder: "border-red-700",
      primaryLightestBg: "bg-red-900/30",
      ring: "focus:ring-red-500",
    },
  },
  'dark-green': {
    name: "Dark Green",
    colors: {
      // FIX: Reference `baseThemes` instead of `themes` to avoid using a variable during its declaration.
      ...baseThemes['dark-sky'].colors,
      primary: "bg-green-500",
      primaryAccent: "bg-green-600",
      primaryAccentLight: "bg-green-400",
      primaryMuted: "text-green-400",
      primaryMutedBg: "bg-green-900/50",
      primaryBorder: "border-green-700",
      primaryLightestBg: "bg-green-900/30",
      ring: "focus:ring-green-500",
    },
  },
  'dark-violet': {
    name: "Dark Violet",
    colors: {
      // FIX: Reference `baseThemes` instead of `themes` to avoid using a variable during its declaration.
      ...baseThemes['dark-sky'].colors,
      primary: "bg-violet-500",
      primaryAccent: "bg-violet-600",
      primaryAccentLight: "bg-violet-400",
      primaryMuted: "text-violet-400",
      primaryMutedBg: "bg-violet-900/50",
      primaryBorder: "border-violet-700",
      primaryLightestBg: "bg-violet-900/30",
      ring: "focus:ring-violet-500",
    },
  },
};
